/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "./"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_WIN32 1
//#define CONFIG_PROFILER 1
#define QEMU_VERSION "0.9.1"
#define CONFIG_SDL 1
#define CONFIG_UNAME_RELEASE ""
#define HOST_ARM_CROSS 1
#define DYNAMIC_TB 1
//#define DEBUG_PCALL 1
//#define DEBUG_EXEC 1
//#define DEBUG_SIGNAL 1
//#define DEBUG_MALLOC 1
#define DEBUG_FLUSH 1
#define NO_WATCHPOINTS 1
